name: QC Checks

on:
  push:
    branches: [main, renovate/**]
  pull_request:
    branches: [main, renovate/**]

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    name: QC Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Use PHP 8.4
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.4
          coverage: none
          tools: composer, cs2pr

      - name: Install
        run: |
          composer install
          ./vendor/squizlabs/php_codesniffer/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard

      - name: Check composer.json
        run: composer validate

      - name: PHPStan checks
        run: vendor/bin/phpstan analyse

      - name: PHPCS checks
        continue-on-error: true
        run: vendor/squizlabs/php_codesniffer/bin/phpcs --standard=./phpcs.xml --no-cache --parallel=1 --report-full --report-checkstyle=./phpcs-report.xml ./src ./tests

      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml

  tests:
    name: Tests PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.4, 8.5]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer

      - name: Install
        run: |
          composer install
          ./vendor/squizlabs/php_codesniffer/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard

      - name: PHPUnit tests
        run: vendor/bin/phpunit
